# Generated by Django 5.0.2 on 2024-02-28 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krishna', '0006_auto_20200808_1207'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CName', models.CharField(max_length=200)),
                ('CEmail', models.EmailField(max_length=254)),
                ('CPnumber', models.IntegerField()),
                ('CMessage', models.CharField(max_length=200)),
            ],
        ),
    ]
