# Generated by Django 5.0.2 on 2024-03-03 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('krishna', '0009_itemmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemModel',
            new_name='PaymentModel',
        ),
        migrations.DeleteModel(
            name='Contactus',
        ),
    ]
