# Generated by Django 5.0.2 on 2024-03-05 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('krishna', '0011_contactus_rename_paymentmodel_itemmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contactus',
        ),
    ]
