# Generated by Django 4.2.3 on 2024-02-21 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=200)),
                ('Cnf_password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Manager_registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=200)),
                ('Cnf_password', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='DataSignup',
        ),
    ]
